---

- name: Gather variables for '{{ cloud_product }}'
  include_vars: "{{ cloud_product }}.yml"

- name: Check subunit tools installed
  command: "subunit2junitxml --help"
  register: _subunit_tools
  failed_when: false
  changed_when: false

- include_tasks: install_dependencies.yml
  when: _subunit_tools.rc != 0

- name: Generate xml subunit results
  shell: "subunit2junitxml {{ tempest_results_subunit }} > {{ subunit_xml_results }}"
  changed_when: false
  failed_when: false

- name: Generate html subunit results
  command: "subunit2html {{ tempest_results_subunit }} {{ subunit_html_results }}"
  changed_when: false
  failed_when: false

- name: Get results from subunit
  command: "subunit-stats {{ tempest_results_subunit }}"
  failed_when: false
  changed_when: false
  register: _test_results

- name: Process test results from subunit
  set_fact:
    tempest_test_results: "{{ tempest_test_results | default({}) | combine({item.split()[0] | lower: item.split()[-1]}) }}"
  when: "'tests' in item"
  loop: "{{ _test_results.stdout_lines }}"
  loop_control:
    label: "{{ item.split()[0] | lower }}: {{ item.split()[-1] }}"

- name: Fail if any tempest test has failed
  fail:
    msg: "{{ tempest_test_results.failed }} tests failed."
  when:
    - tempest_test_results is defined
    - tempest_test_results.failed | int > 0
