#
# (c) Copyright 2018 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: "Ensure host in /etc/hosts"
  lineinfile:
    dest: "/etc/hosts"
    insertbefore: "BOF"
    line: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ ansible_default_ipv4.address }}      {{ ansible_hostname }}"
    - "::1     {{ ansible_hostname }}"

- name: "Ensure NTP installed"
  package:
    name: ntp
    state: present

- name: Ensure NTP is enabled
  service:
    name: "ntpd"
    state: started
    enabled: yes

- name: Ensure SES repos present
  zypper_repository:
    name: "{{ item.name }}"
    repo: "{{ item.repo }}"
  with_items:
    - name: "SUSE-Enterprise-Storage-{{ ses_version }}-Pool"
      repo: "{{ ses_repo_server }}/repos/x86_64/SUSE-Enterprise-Storage-{{ ses_version }}-Pool/"
    - name: "SUSE-Enterprise-Storage-{{ ses_version }}-Updates"
      repo: "{{ ses_repo_server }}/repos/x86_64/SUSE-Enterprise-Storage-{{ ses_version }}-Updates/"
  when: ses_add_zypper_repos
