#
# (c) Copyright 2019 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
---

- name: Drop openstack-bmc service file
  template:
    src: "openstack-bmc.service.j2"
    dest: "/usr/lib/systemd/system/openstack-bmc.service"
  notify:
    - Restart openstack-bmc

- name: Disable wickedd-dhclient
  service:
    name: "{{ item }}"
    state: "stopped"
    enabled: no
  loop:
    - wickedd-dhcp4
    - wickedd-dhcp6
