---

- include_tasks: set_node_name_{{ pxe_boot_enabled | ternary('crowbar', 'os') }}_provisioned.yml

- name: Create crowbar node list properly sorted
  set_fact:
    crowbar_node_list: "{{ crowbar_node_list | default('crowbar.' + cloud_fqdn) }} {{ hostvars[item]['crowbar_node_name'] }}"
  loop: "{{ groups['cloud_virt_hosts'] }}"
  delegate_to: "{{ cloud_env }}"
  run_once: true

- name: Fill in custom crowbar node list in mkcloud.conf
  lineinfile:
    dest: "{{ admin_mkcloud_config_file }}"
    regexp: "^export custom_crowbar_node_order"
    line: "export custom_crowbar_node_order='{{ crowbar_node_list }}'"
    state: present
  delegate_to: "{{ cloud_env }}"
  run_once: true

- name: Reserve node admin IP addresses in Crowbar
  include_tasks: reserve_admin_ip.yml

- name: Register nodes
  include_tasks: register_nodes.yml
  when: not pxe_boot_enabled
