
---

# Disable cinder LVM device group in Crowbar
cinder_disk_enabled: False

# Disable swiftpac device group in Crowbar
swiftpac_disk_enabled: False

# Start value for the third octet for the generated subnet prefixes and also
# start of generated VLAN IDs for Ardana networks
gen_subnet_start: 124
# Start value for the fourth octet for the generated server IP addresses
gen_ip_start: 10
# Gap to be left between the generated IP for the admin node and the rest of the nodes
gen_ip_gap: 71
# Gap to be left between the generated IP for the bmc node and the rest of the nodes
# As crowbar bmc nodes are also on the admin network this gap needs to fit the values on network.json bmc network range
bmc_ip_gap: 80
cloud_iso_name: "{{ (cloudsource[-1] == '7') | ternary('SUSE-OpenStack-Cloud-7', 'SUSE-OpenStack-Cloud-Crowbar-' ~ cloudsource[-1]) }}"
